POST http://127.0.0.1:8000/signup/
Content-Type: application/json

{ "email": "kamal.hamza2@outlook.com", "password": "Microsofty1" }

####

POST http://127.0.0.1:8000/login/
Content-Type: application/json

{ "email": "kamal.hamza2@outlook.com", "password": "Microsofty1" }

####

POST http://127.0.0.1:8000/create-list-room/
Content-Type: application/json
Authorization: Token bc5080857047f9f62f0bfb98b50dc566a7448527

{ "name": "Basketball Court 2", "price": "25.00", "capacity": 100, "isAvaliableForBooking": false }

####

GET http://127.0.0.1:8000/create-list-room/
Authorization: Token bc5080857047f9f62f0bfb98b50dc566a7448527

####

GET http://127.0.0.1:8000/create-list-room/1/
Authorization: Token bc5080857047f9f62f0bfb98b50dc566a7448527